version: '3.3'

volumes:
  foodgram_data:
  foodgram_media:
  foodgram_static:

services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - foodgram_static:/app/result_build/


  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_media:/app/media
      - foodgram_static:/static



  db:
    container_name: db-foodgram
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - foodgram_data:/var/lib/postgresql/data


  backend:
    container_name: foodgram-backend
    build: ../backend/foodgram/
    env_file: ../.env
    volumes:
      - foodgram_static:/backend_static/
      - foodgram_media:/app/media/
    depends_on:
      - db
