# Generated by Django 3.2.3 on 2024-09-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipetag_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='D:\\Dev\\foodgram\\backend\\foodgram/media/', verbose_name='Картинка рецепта'),
        ),
    ]
