# Generated by Django 3.2.3 on 2024-09-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20240919_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
