# Generated by Django 3.2.3 on 2024-09-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='users/avatars/', verbose_name='Аватар пользователя'),
            preserve_default=False,
        ),
    ]
