# Generated by Django 3.2.3 on 2024-09-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='D:\\Dev\\foodgram\\backend\\foodgram/media/', verbose_name='Аватар пользователя'),
        ),
    ]
